const defaultLinkedIn = 'https://www.linkedin.com/company/gdsc-mgm/';

export const LeadData = [
    {
        id: 'Lead',
        name: 'Sahil Ambure',
        profile: 'SahilAmbure.jpg',
        linkedin: 'https://www.linkedin.com/in/sahil-ambure/',
    }
];


export const CoreTeamData = [
    {
        id: 'Lead1',
        name: 'Sahil Bodke',
        profile: 'SahilBodke.jpg',
        position: 'Co-Lead GDSC',
        department: 'Co-Lead',
        gender: 'He',
        linkedin: 'http://www.linkedin.com/in/sahil-bodke-45570a251',
    },
    {
        id: 'Lead2',
        name: 'Himanshu Bhoir',
        profile: 'HimanshuBhoir.png',
        position: 'Project Head Web',
        department: 'Web',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: 'Lead3',
        name: 'Tanmay Bhole',
        profile: 'TanmayBhole.jpg',
        position: 'Project Head App',
        department: 'App',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/tanmay-bhole-0453a7262/',
    },
    {
        id: 'Lead4',
        name: 'Ritesh Mishra',
        profile: 'RiteshMishra.jpg',
        position: 'Project Head AI/ML',
        department: 'AI/ML',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/ritesh-mishra-70ab7822a',
    },
    {
        id: 'Lead5',
        name: 'Shruti Kulkarni',
        profile: 'ShrutiKulkarni.jpg',
        position: 'Treasurer',
        department: 'Treasurer',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/shruti-kulkarni-523443241/',
    },
    {
        id: 'Lead6',
        name: 'Vibhanshu Dubey',
        profile: 'VibhanshuDubey.jpg',
        position: 'Marketing Head',
        department: 'Marketing',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/vibhanshu-dubey-0a692b284',
    },
    {
        id: 'Lead7',
        name: 'Kunal More',
        profile: 'KunalMore.jpg',
        position: 'Events Head',
        department: 'Event',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/kunal-more-7b6404285/',
    },
    {
        id: 'Lead8',
        name: 'Saachi Gadling',
        profile: 'SaachiGadling.png',
        position: 'Creative Head',
        department: 'Creative',
        gender: 'She',
        linkedin: 'http://www.linkedin.com/in/saachi-gadling',
    }, 
    {
        id: 'Lead9',
        name: 'Anushka Kadam',
        profile: 'AnushkaKadam.jpeg',
        position: 'Media Head',
        department: 'Media',
        gender: 'She',
        linkedin: 'http://www.linkedin.com/in/anushka-kadam-66138b1ab',
    },
];


export const Teams = [
    {
        id: '1',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'AryanNipane.png',
        linkedin: 'https://www.linkedin.com/in/aryannipane/',
        gender: 'He',
    },
    {
        id: '2',
        name: 'Omkar Mandave',
        department: 'App',
        position: 'Co-head',
        profile: 'OmkarMandave.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/omkar-mandave-598708260',
    },
    {
        id: '3',
        name: 'Ayaaz Shekhani',
        department: 'AI/ML',
        position: 'Co-head',
        profile: 'AyaazShekhani.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/ayaaz-shekhani-601115235/',
    },
    {
        id: '4',
        name: 'Pravesh Lohar',
        department: 'Treasurer',
        position: 'Co-head',
        profile: 'PraveshLohar.jpg',
        gender: 'He',
        linkedin: 'https://linkedin.com/in/pravesh-lohar21',
    },
    {
        id: '5',
        name: 'Vivek Shingne',
        department: 'Marketing',
        position: 'Co-head',
        profile: 'VivekShingne.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/vivek-shingne-349563233',
    },
    {
        id: '6',
        name: 'Arya Singasane',
        department: 'Event',
        position: 'Co-head',
        profile: 'AryaSingasane.jpg',
        gender: 'She',
        linkedin: 'http://www.linkedin.com/in/arya-singasane-9b4a2a22a',
    },
    {
        id: '7',
        name: 'Sejal Billur',
        department: 'Media',
        position: 'Co-head',
        profile: 'SejalBillur.jpeg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/sejal-billur-b76988287',
    },
    {
        id: '8',
        name: 'Devesh Patil ',
        department: 'Creative',
        position: 'Team',
        profile: 'DeveshPatilNew2.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/devesh-patil-113036246',
    },
    {
        id: '9',
        name: 'Pranav Ambadkar',
        department: 'Web',
        position: 'Teaam',
        profile: 'PranavAmbadkar.jpeg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/pranav-ambadkar-25298520a/',
    },
    {
        id: '2',
        name: 'Deepak Kamble',
        department: 'App',
        position: 'Team',
        profile: 'DeepakKamble.jpeg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/deepak-kamble-21139325b',
    },
    {
        id: '10',
        name: 'Harshal Tupe',
        department: 'Web',
        position: 'Team',
        profile: 'HarshalTupe.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/harshal-tupe-00130b204',
    },
    {
        id: '1',
        name: 'Siddhesh Pakhare',
        department: 'Web',
        position: 'Team',
        profile: 'SiddheshPakhre.jpg',
        linkedin: 'https://www.linkedin.com/in/siddhesh-pakhare-462970266/',
        gender: 'He',
    },
    {
        id: '3',
        name: 'Rashmi Choudhary',
        department: 'Web',
        position: 'Team',
        profile: 'RashmiChoudhary.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/rashmi-choudhary-9670a225b',
    },
    {
        id: '4',
        name: 'Ekta Anturkar',
        department: 'Creative',
        position: 'Team',
        profile: 'EktaAnturkar.jpeg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/ektaanturkar-b482b4282',
    },
    {
        id: '5',
        name: 'Hemangi Patil',
        department: 'Creative',
        position: 'Team',
        profile: 'HemangiPatil.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/hemangi-patil-b86852292',
    },
    {
        id: '6',
        name: 'Indrayanee Sawant',
        department: 'AI/ML',
        position: 'Team',
        profile: 'IndrayneeSawant.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/indrayani-sawant-6769b9256',
    },
    {
        id: '7',
        name: 'Tejraj Jadhav',
        department: 'AI/ML',
        position: 'Team',
        profile: 'TejrajJadhav.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/tejraj-jadhav-07a507260',
    },
    {
        id: '8',
        name: 'Jyoti Pal ',
        department: 'App',
        position: 'Team',
        profile: 'JyotiPal.jpg',
        gender: 'She',
        linkedin: 'http://linkedin.com/in/jyoti-pal-4989b9292/',
    },
    {
        id: '9',
        name: 'Om Gharat',
        department: 'Media',
        position: 'Team',
        profile: 'OmGharat.jpeg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/om-gharat-a82aa31b0',
    },
    {
        id: '10',
        name: 'Ronak Waghela',
        department: 'Events',
        position: 'Team',
        profile: 'RonakWaghela.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/ronak-waghela-932ab0219/',
    },
    {
        id: '1',
        name: 'Sakshi Mokal',
        department: 'Events',
        position: 'Team',
        profile: 'SakshiMokal.jpg',
        linkedin: 'https://www.linkedin.com/in/sakshi-mokal-532b07229',
        gender: 'She',
    },
    {
        id: '2',
        name: 'Soham Sharma',
        department: 'Events',
        position: 'Team',
        profile: 'SohamSharma.jpg',
        gender: 'He',
        linkedin: 'https://in.linkedin.com/in/soham-sharma-6b80b7229',
    },
    {
        id: '3',
        name: 'Soubiya Mullaji',
        department: 'Events',
        position: 'Team',
        profile: 'SoubiyaMullaji.jpeg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/soubiyamullaji',
    },
    {
        id: '4',
        name: 'Tejas Prasade ',
        department: 'Events',
        position: 'Team',
        profile: 'TejasPrasade.jpg',
        gender: 'He',
        linkedin: 'http://www.linkedin.com/in/tejasprasade',
    },
    {
        id: '5',
        name: 'Sanjana Tikone',
        department: 'AI/ML',
        position: 'Team',
        profile: 'SanjanaTikone.jpg',
        gender: 'She',
        linkedin: 'http://www.linkedin.com/in/sanjana-tikone-654201292',
    },
    {
        id: '6',
        name: 'Rashmi Choudhary',
        department: 'Web',
        position: 'Team',
        profile: 'RashmiChoudhary.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/rashmi-choudhary-9670a225b',
    },
    {
        id: '7',
        name: 'Vishakha Pingat',
        department: 'Events',
        position: 'Team',
        profile: 'VishakhaPingat.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/vishakha-pingat-30175125a',
    },
    //
    {
        id: '8',
        name: 'Raj Ghonge',
        department: 'Media',
        position: 'Team',
        profile: 'RajGhonge.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/raj-ghonge-77b87b28a/',
    },
    {
        id: '9',
        name: 'Divyesh Patil',
        department: 'Creative',
        position: 'Team',
        profile: '',
        gender: 'He',
        linkedin: '',
    },
    {
        id: '10',
        name: 'Amey Patil',
        department: 'Creative',
        position: 'Team',
        profile: '',
        gender: 'He',
        linkedin: defaultLinkedIn,
    },
    {
        id: '11',
        name: 'Siddhesh Mhatre',
        department: 'Creative',
        position: 'Team',
        profile: 'SiddheshMhatre.jpg',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/siddhesh-mhatre-4891b3233/',
    },
    {
        id: '12',
        name: 'Vaidehi Chandre',
        department: 'Creative',
        position: 'Team',
        profile: 'VaidehiChandre.jpeg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/vaidehi-chandre-9ab7a2212/',
    },
    
];